Adding missing complain on non set ROOTSOURCES, fixing order of CMake includes in script

diff --git a/analyzer/preparing-environment-for-pkg b/analyzer/preparing-environment-for-pkg
--- a/analyzer/preparing-environment-for-pkg
+++ b/analyzer/preparing-environment-for-pkg
@@ -13,6 +13,12 @@ then
   exit 1
 fi
 
+if [ -z "$ROOTSOURCES" ]
+then
+  echo "ROOTSYS not set"
+  exit 1
+fi
+
 pkg_name="$1"
 pkg_dir="$2"
 target_cmake="pkg-source/CMakeLists.txt"
@@ -22,8 +28,9 @@ mkdir -p ~/.cache/root-pkgs/$pkg_name
 cd ~/.cache/root-pkgs/$pkg_name
 
 cp -r "$pkg_dir" pkg-source
-echo -e "cmake_minimum_required(VERSION 3.7)\n$(cat $target_cmake)" > "$target_cmake"
 echo -e "include(RootFramework)\n$(cat $target_cmake)" > "$target_cmake"
+#echo -e "list(APPEND CMAKE_MODULE_PATH ${ROOTSOURCES}/cmake)" > "$target_cmake"
+echo -e "cmake_minimum_required(VERSION 3.7)\n$(cat $target_cmake)" > "$target_cmake"
 
 mkdir build
 cd build
